# Proyecto Final - Analisis Exploratorio de Datos (EDA)

**Tema:** Analisis de ventas y rentabilidad con el dataset Sample Superstore.

**Objetivo:** Transformar un conjunto de datos crudo en informacion accionable mediante un flujo de trabajo profesional con Python, Pandas, NumPy y Matplotlib.

**Integrantes:**
1. Andrea Camila Briones Galarza
2. Santiago Jesús Faican Quilligana
3. Edgar Teodoro Ulloa Vázquez

# PARTE 1 - Edgar Ulloa: carga, exploración y limpieza

**Responsable:** Edgar Teodoro Ulloa Vázquez  
**Objetivo:** preparar el dataset para que los otros integrantes puedan trabajar sobre datos limpios.

## 1. Preparación del proyecto

En primer lugar se realiza la preparación del respositori en github para la realización del proyecto

Clonamos el proyecto a github

In [36]:
!git clone https://github.com/itqpython/ProyectoFinalITQ.git
%cd ProyectoFinalITQ

Cloning into 'ProyectoFinalITQ'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 33 (delta 11), reused 3 (delta 1), pack-reused 0 (from 0)
Receiving objects: 100% (33/33), 381.56 KiB | 6.81 MiB/s, done.
Resolving deltas: 100% (11/11), done.
/content/ProyectoFinalITQ/ProyectoFinalITQ/ProyectoFinalITQ/ProyectoFinalITQ/ProyectoFinalITQ

Identificación de usuario en github

In [37]:
!git config --global user.name "Edgar Teodoro Ulloa Vázquez"
!git config --global user.email "edgar.ulloa@itq.edu.ec"

Creación del espacio en github

In [38]:
!mkdir -p dataset notebook graficos informe resultados

## 2. Importar librerías

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

# 3. Cargar dataset original

In [41]:
df = pd.read_csv("dataset/SampleSuperstore.csv")
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

# 4. Exploración inicial

In [42]:
# Cantidad de filas y columnas
df.shape

(9994, 13)

In [43]:
# Resumen de información contenida en el dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Ship Mode     9994 non-null   object
 1   Segment       9994 non-null   object
 2   Country       9994 non-null   object
 3   City          9994 non-null   object
 4   State         9994 non-null   object
 5   Postal Code   9994 non-null   int64
 6   Region        9994 non-null   object
 7   Category      9994 non-null   object
 8   Sub-Category  9994 non-null   object
 9   Sales         9994 non-null   float64
 10  Quantity      9994 non-null   int64
 11  Discount      9994 non-null   float64
 12  Profit        9994 non-null   float64
dtypes: float64(3), int64(2), object(8)
memory usage: 1015.1+ KB

In [44]:
# Estadísticos descriptivos de los datos
df.describe()

        Postal Code         Sales     Quantity     Discount       Profit
count   9994.000000   9994.000000  9994.000000  9994.000000  9994.000000
mean   55190.379428    229.858001     3.789574     0.156203    28.656896
std    32063.693350    623.245101     2.225110     0.206452   234.260108
min     1040.000000      0.444000     1.000000     0.000000 -6599.978000
25%    23223.000000     17.280000     2.000000     0.000000     1.728750
50%    56430.500000     54.490000     3.000000     0.200000     8.666500
75%    90008.000000    209.940000     5.000000     0.200000    29.364000
max    99301.000000  22638.480000    14.000000     0.800000  8399.976000

In [45]:
# Cantidad de nulos
df.isnull().sum()

Ship Mode       0
Segment         0
Country         0
City            0
State           0
Postal Code     0
Region          0
Category        0
Sub-Category    0
Sales           0
Quantity        0
Discount        0
Profit          0
dtype: int64

In [47]:
# Cantidad de datos duplicados
df.duplicated().sum()

np.int64(17)

# 5. Limpieza del dataset

In [48]:
df_limpio = df.copy()

# Limpiar nombres de columnas
df_limpio.columns = [columna.strip().replace(" ", "_").replace("-", "_")
   for columna in df_limpio.columns]

# Limpiar espacios en columnas de texto
for columna in df_limpio.select_dtypes(include="object").columns:
    df_limpio[columna] = df_limpio[columna].str.strip()

# Eliminar duplicados
duplicados = df_limpio.duplicated().sum()
df_limpio = df_limpio.drop_duplicates().reset_index(drop=True)

print("Duplicados eliminados:", duplicados)
print("Tamaño final:", df_limpio.shape)

df_limpio.head()

Duplicados eliminados: 17
Tamaño final: (9977, 13)

,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

# 6. Crear variables nuevas

Como el dataset original carece de una columna fecha, se crea una fecha ficticia en función de la secuencia de los registros para efectos de validar la temporalidad, además de otras varialbles útiles para el análisis final de la información.

In [49]:
df_limpio["Fecha_Estimada"] = pd.to_datetime("2014-01-01") + pd.to_timedelta(df_limpio.index // 10,unit="D")

df_limpio["Anio"] = df_limpio["Fecha_Estimada"].dt.year
df_limpio["Mes"] = df_limpio["Fecha_Estimada"].dt.month
df_limpio["Dia_Semana"] = df_limpio["Fecha_Estimada"].dt.day_name()

df_limpio["Margen_Profit"] = np.where(df_limpio["Sales"] != 0,df_limpio["Profit"] / df_limpio["Sales"],0)

df_limpio["Venta_Promedio_Unidad"] = np.where(df_limpio["Quantity"] != 0,df_limpio["Sales"] / df_limpio["Quantity"],0)

df_limpio.head()

,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Sales,Quantity,Discount,Profit,Fecha_Estimada,Anio,Mes,Dia_Semana,Margen_Profit,Venta_Promedio_Unidad
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136,2014-01-01,2014,1,Wednesday,0.1600,130.9800
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820,2014-01-01,2014,1,Wednesday,0.3000,243.9800
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714,2014-01-01,2014,1,Wednesday,0.4700,7.3100
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310,2014-01-01,2014,1,Wednesday,-0.4000,191.5155
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164,2014-01-01,2014,1,Wednesday,0.1125,11.1840

#   7. Guardar dataset limpio

In [50]:
df_limpio.to_csv("dataset/SampleSuperstore_limpio.csv", index=False)
print("Dataset limpio guardado correctamente.")

Dataset limpio guardado correctamente.